/* Auto-generated by tools/lqr_design.py -- do not edit by hand.
 *
 * Cart-pole LQR, acceleration input, with a cart position-error integrator so
 * the cart is pulled to x_ref (default: middle of travel) and a small upright
 * calibration bias cannot make it creep. State s = [x, xdot, theta, thetadot,
 * xi] in SI units; theta is from upright, positive = pole tips toward +x
 * (RIGHT); xi = integral of (x - x_ref) in m*s. Input u = xddot (m/s^2). Law:
 *
 *     u = -( K0*(x - x_ref) + K1*xdot + K2*theta + K3*thetadot + K4*xi )
 *
 * Model (augmented, xi_dot = x - x_ref):
 *     A = [ 0 1 0 0 0 ; 0 0 0 0 0 ; 0 0 0 1 0 ; 0 0 g/l 0 0 ; 1 0 0 0 0 ]
 *     B = [ 0 ; 1 ; 0 ; -1/l ; 0 ]
 *
 * Parameters:
 *     l = 0.15 m   (pivot -> pole center of mass; half a uniform rod's length)
 *     g = 9.81 m/s^2
 * Weights:
 *     Q = diag([1.0, 0.1, 100.0, 10.0, 1.0])   R = [0.5]
 *       Q0 x        cart position pull toward x_ref (via K0)
 *       Q1 xdot     light cart-velocity damping
 *       Q2 theta    upright angle penalty (main aggressiveness knob)
 *       Q3 thetadot angle-rate damping
 *       Q4 xi       position-error integral weight (bias rejection / centering)
 *       R           control-effort penalty (larger = gentler cart motion)
 * Solver: numpy Hamiltonian eigen-decomposition (scipy not installed)
 * Regenerate with:
 *     python3 tools/lqr_design.py --l 0.15 --q 1.0,0.1,100.0,10.0 --qxi 1.0 --r 0.5
 */
#ifndef LQR_GAINS_H
#define LQR_GAINS_H

#define LQR_K0 -3.865449f   /* (x - x_ref) error, 1/m */
#define LQR_K1 -4.575581f   /* xdot, s/m */
#define LQR_K2 -38.422375f   /* theta, 1/rad */
#define LQR_K3 -6.286093f   /* thetadot, s/rad */
#define LQR_K4 -1.414214f   /* xi = integral of (x - x_ref), 1/(m*s) */

#endif /* LQR_GAINS_H */
